// <auto-generated />
using System;
using MccIntakeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MccIntakeService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MccIntakeDbContext))]
    [Migration("20260904044039_AddTankManagementAndTemperatures")]
    partial class AddTankManagementAndTemperatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ArrivalAtLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalQuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalQuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_consignments_reference");

                    b.HasIndex("SocietyId", "ArrivalDate")
                        .HasDatabaseName("ix_consignments_society_arrival_date");

                    b.ToTable("consignments", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.ConsignmentCan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CanLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CanNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("QuantityLitres")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentId", "CanNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_consignment_cans_consignment_can_number");

                    b.ToTable("consignment_cans", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Dispatch.DispatchNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BowserRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("DispatchedAtLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DispatchedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("FatPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KqColour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Snf")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StabilityGrade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalQuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchDate")
                        .HasDatabaseName("ix_dispatch_notes_date");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_notes_reference");

                    b.ToTable("dispatch_notes", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Dispatch.DispatchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DispatchNoteId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FillNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("QuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TankId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchNoteId", "TankId")
                        .IsUnique()
                        .HasDatabaseName("ux_dispatch_sources_note_tank");

                    b.HasIndex("TankId", "FillNumber")
                        .HasDatabaseName("ix_dispatch_sources_tank_fill");

                    b.ToTable("dispatch_sources", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Factory.ArrivalScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ArrivedAtLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ColourPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("DispatchNoteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FailedParameters")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ScreenedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ScreenedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("SmellPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("TemperaturePassed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchNoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_arrival_screenings_dispatch_note");

                    b.ToTable("arrival_screenings", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Factory.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ArrivalScreeningId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BatchDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DispatchNoteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalScreeningId")
                        .IsUnique();

                    b.HasIndex("BatchDate")
                        .HasDatabaseName("ix_batches_date");

                    b.HasIndex("DispatchNoteId")
                        .IsUnique()
                        .HasDatabaseName("ux_batches_dispatch_note");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_batches_reference");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.QualityTests.AlcoholStageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("QualityTestId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("QualityTestId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ux_quality_test_alcohol_stages_order");

                    b.ToTable("quality_test_alcohol_stages", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.QualityTests.QualityTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("ColourOk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CorrectedClr")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("FailedParameter")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FailedValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("FatPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("KqColour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PassedAlcoholAt")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("RawLactometerReading")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("SmellOk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Snf")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StabilityGrade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("TasteOk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("TestedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("TotalSolids")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("WaterPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_quality_tests_consignment");

                    b.ToTable("quality_tests", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Societies.Society", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CanLabelPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_societies_code");

                    b.ToTable("societies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f0f6f1a-0001-4a2b-9c3d-000000000001"),
                            CanLabelPrefix = "KC",
                            Code = "KC",
                            ContactNumber = "+94 81 222 3344",
                            ContactPerson = "Sunil Perera",
                            IsActive = true,
                            Name = "Kandy Co-operative Dairy Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0002-4a2b-9c3d-000000000002"),
                            CanLabelPrefix = "MT",
                            Code = "MT",
                            ContactNumber = "+94 66 222 5566",
                            ContactPerson = "Kamala Ranasinghe",
                            IsActive = true,
                            Name = "Matale Farmers' Milk Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0003-4a2b-9c3d-000000000003"),
                            CanLabelPrefix = "NW",
                            Code = "NW",
                            ContactNumber = "+94 52 222 7788",
                            ContactPerson = "Ravi Kumar",
                            IsActive = true,
                            Name = "Nuwara Eliya Highland Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0004-4a2b-9c3d-000000000004"),
                            CanLabelPrefix = "BD",
                            Code = "BD",
                            ContactNumber = "+94 55 222 9900",
                            ContactPerson = "Anoma Jayasuriya",
                            IsActive = true,
                            Name = "Badulla Uva Milk Society"
                        });
                });

            modelBuilder.Entity("MccIntakeService.Domain.Sync.SyncedRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientRecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ResultReference")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SyncedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientRecordId")
                        .IsUnique()
                        .HasDatabaseName("ux_synced_records_client_record");

                    b.ToTable("synced_records", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.ChillingTank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CapacityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("FillNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("LastClosedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_chilling_tanks_code");

                    b.ToTable("chilling_tanks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a1c2b30-0001-4d5e-8f60-000000000001"),
                            CapacityLitres = 5000m,
                            Code = "T1",
                            FillNumber = 1,
                            Name = "Chilling Tank 1",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9a1c2b30-0002-4d5e-8f60-000000000002"),
                            CapacityLitres = 5000m,
                            Code = "T2",
                            FillNumber = 1,
                            Name = "Chilling Tank 2",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9a1c2b30-0003-4d5e-8f60-000000000003"),
                            CapacityLitres = 3000m,
                            Code = "T3",
                            FillNumber = 1,
                            Name = "Chilling Tank 3",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.TankPour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FillNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("PourDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PouredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PouredBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("QuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TankId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_tank_pours_consignment");

                    b.HasIndex("TankId", "FillNumber")
                        .HasDatabaseName("ix_tank_pours_tank_fill");

                    b.HasIndex("TankId", "PourDate")
                        .HasDatabaseName("ix_tank_pours_tank_date");

                    b.ToTable("tank_pours", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.TankTemperatureReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Celsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FillNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("TankId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TankId", "RecordedAtUtc")
                        .HasDatabaseName("ix_tank_temperature_readings_tank_time");

                    b.ToTable("tank_temperature_readings", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Models.MilkCollectionCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MilkCollectionCenters");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Societies.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Society");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.ConsignmentCan", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Consignments.Consignment", null)
                        .WithMany("Cans")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MccIntakeService.Domain.Dispatch.DispatchSource", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Dispatch.DispatchNote", null)
                        .WithMany("Sources")
                        .HasForeignKey("DispatchNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MccIntakeService.Domain.Tanks.ChillingTank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Factory.ArrivalScreening", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Dispatch.DispatchNote", "DispatchNote")
                        .WithOne()
                        .HasForeignKey("MccIntakeService.Domain.Factory.ArrivalScreening", "DispatchNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispatchNote");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Factory.Batch", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Factory.ArrivalScreening", null)
                        .WithOne("Batch")
                        .HasForeignKey("MccIntakeService.Domain.Factory.Batch", "ArrivalScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MccIntakeService.Domain.Dispatch.DispatchNote", "DispatchNote")
                        .WithMany()
                        .HasForeignKey("DispatchNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispatchNote");
                });

            modelBuilder.Entity("MccIntakeService.Domain.QualityTests.AlcoholStageRecord", b =>
                {
                    b.HasOne("MccIntakeService.Domain.QualityTests.QualityTest", null)
                        .WithMany("AlcoholStages")
                        .HasForeignKey("QualityTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MccIntakeService.Domain.QualityTests.QualityTest", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Consignments.Consignment", "Consignment")
                        .WithOne()
                        .HasForeignKey("MccIntakeService.Domain.QualityTests.QualityTest", "ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consignment");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.TankPour", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Consignments.Consignment", "Consignment")
                        .WithOne()
                        .HasForeignKey("MccIntakeService.Domain.Tanks.TankPour", "ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MccIntakeService.Domain.Tanks.ChillingTank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignment");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.TankTemperatureReading", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Tanks.ChillingTank", "Tank")
                        .WithMany("TemperatureReadings")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.Navigation("Cans");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Dispatch.DispatchNote", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Factory.ArrivalScreening", b =>
                {
                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MccIntakeService.Domain.QualityTests.QualityTest", b =>
                {
                    b.Navigation("AlcoholStages");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Tanks.ChillingTank", b =>
                {
                    b.Navigation("TemperatureReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
