// <auto-generated />
using System;
using MccIntakeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MccIntakeService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MccIntakeDbContext))]
    partial class MccIntakeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ArrivalAtLocal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegisteredBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("SocietyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalQuantityKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalQuantityLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_consignments_reference");

                    b.HasIndex("SocietyId", "ArrivalDate")
                        .HasDatabaseName("ix_consignments_society_arrival_date");

                    b.ToTable("consignments", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.ConsignmentCan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CanLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CanNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ConsignmentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("QuantityLitres")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsignmentId", "CanNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_consignment_cans_consignment_can_number");

                    b.ToTable("consignment_cans", (string)null);
                });

            modelBuilder.Entity("MccIntakeService.Domain.Societies.Society", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CanLabelPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_societies_code");

                    b.ToTable("societies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f0f6f1a-0001-4a2b-9c3d-000000000001"),
                            CanLabelPrefix = "KC",
                            Code = "KC",
                            ContactNumber = "+94 81 222 3344",
                            ContactPerson = "Sunil Perera",
                            IsActive = true,
                            Name = "Kandy Co-operative Dairy Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0002-4a2b-9c3d-000000000002"),
                            CanLabelPrefix = "MT",
                            Code = "MT",
                            ContactNumber = "+94 66 222 5566",
                            ContactPerson = "Kamala Ranasinghe",
                            IsActive = true,
                            Name = "Matale Farmers' Milk Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0003-4a2b-9c3d-000000000003"),
                            CanLabelPrefix = "NW",
                            Code = "NW",
                            ContactNumber = "+94 52 222 7788",
                            ContactPerson = "Ravi Kumar",
                            IsActive = true,
                            Name = "Nuwara Eliya Highland Society"
                        },
                        new
                        {
                            Id = new Guid("6f0f6f1a-0004-4a2b-9c3d-000000000004"),
                            CanLabelPrefix = "BD",
                            Code = "BD",
                            ContactNumber = "+94 55 222 9900",
                            ContactPerson = "Anoma Jayasuriya",
                            IsActive = true,
                            Name = "Badulla Uva Milk Society"
                        });
                });

            modelBuilder.Entity("MccIntakeService.Models.MilkCollectionCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MilkCollectionCenters");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Societies.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Society");
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.ConsignmentCan", b =>
                {
                    b.HasOne("MccIntakeService.Domain.Consignments.Consignment", null)
                        .WithMany("Cans")
                        .HasForeignKey("ConsignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MccIntakeService.Domain.Consignments.Consignment", b =>
                {
                    b.Navigation("Cans");
                });
#pragma warning restore 612, 618
        }
    }
}
